name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # 1. El guardia de seguridad (Integración)
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Ejecutar pruebas
        run: pytest tests/

  # 2. El despliegue (Solo ocurre si el paso anterior está verde)
  deploy:
    needs: test  # ESTO ES LA CLAVE: Dice "espera a que test termine bien"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Desplegar en Render
        uses: JorgeLNJunior/render-deploy@v1.0.1
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}